/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.quartz.Scheduler;
import org.quartz.SchedulerException;
import org.quartz.impl.StdSchedulerFactory;

import static org.example.introduction.CustomJobDetailsIndTrigger.jobDetail;
import static org.example.introduction.CustomJobDetailsIndTrigger.trigger;

public class App {

    void main() {
        try {
            Scheduler scheduler = StdSchedulerFactory.getDefaultScheduler();
            scheduler.scheduleJob(jobDetail("job1", "group1"), trigger("trigger1", "group1"));
            scheduler.start();
            Thread.sleep(90L * 1000L);
            scheduler.shutdown();
        } catch (SchedulerException | InterruptedException e) {
            throw new RuntimeException(e);
        }
    }
}
